### ISSUE TITLE
Ability to remove file but keep record

### ISSUE THREAD

**Issue by designway** [davidyell/CakePHP3-Proffer#100]
This is an enhancement!

It is not possible if I want to remove only the file, but keep the record..

An option to add a checkbox named "field_remove" to remove only the file. If form is submitted and checkbox is checked then save all data and removing current file.
if my table upload field is "photo", the remove flag checkbox could be called "photo_remove".

**Comment by davidyell** [comment]
Yes, this functionality doesn't exist in the plugin yet. I'll need to think about if and how I'd like to add it in.

You could do this yourself in your controller, for the meantime.

```php
$data = $this->Examples->patchEntity($data, $this->request->data);
if (isset($this->request->data['remove_file'])) {
    $data->set('photo', null);
    $data->set('photo_dir', null);
}
$this->Examples->save($data);
```

**Comment by SBhojani** [comment]
Any updates on this?

**Comment by davidyell** [comment]
Sorry, I've been busy with work and have had a holiday.

Currently the solution included above will work. I think that adding this into the plugin will be a helpful feature to reduce build-up of files. Also don't forget that there is a cleanup shell task which can remove old images in the meantime.

**Comment by davidyell** [comment]
Relates to #127 

Closing, as this issue is resolved in the documentation now.
