### ISSUE TITLE
thumbnailCropScale

### ISSUE THREAD

**Issue by pontius34** [davidyell/CakePHP3-Proffer#108]
Hi,
i tested the cropping function and i have some improvements you have to do that the images fit best in the thumbnail box. please take a look at it.
There are two more conditions that have to be checked. without the two extra checks, at some situations the images dont fit well in the thumbnail.

http://pastebin.com/ib4qMWpy

**Comment by davidyell** [comment]
Thanks for the issue, any chance that you could provide a PR to the `develop` branch with your changes and ideally a test also.

**Comment by pontius34** [comment]
I dont know how to write a test. 
But i ended up with the following solution: http://pastebin.com/7UXhqjCG
It first checks the orientation. Because i noticed that if the user takes directly a photo from an iphone f.e. than the image needs to be rotated.
Then the image is resized. With a smaller and simple code.
And after that with a simple code to get the croped thumbnail.

**Comment by davidyell** [comment]
I'm having trouble reproducing this issue. Do you have any further details, or an example image I can try?

**Comment by davidyell** [comment]
Closing in favour of #124
