### ISSUE TITLE
Warning about not using Composer

### ISSUE THREAD

**Issue by davidyell** [davidyell/CakePHP3-Proffer#112]
Need to put a note into the installation docs about Composer being a requirement to use the plugin.

* Can reference this, http://book.cakephp.org/3.0/en/plugins.html#installing-a-plugin-with-composer
* Also that non-composer installs are unsupported
* Update readme to have Composer as a requirement

**Comment by ceeram** [comment]
use composer require command instead of manually editing composer.json
