### ISSUE TITLE
The new file name is not registered in the DB

### ISSUE THREAD

**Issue by webme** [davidyell/CakePHP3-Proffer#121]
I use the ```pathClass``` to override the method ```setFilename```

After recording, the images and their thumbnails are saved with the new name. But in the database the field has the value of the original file name.

To solve the problem in ```Proffer\Model\Behavior::beforeSave()``` I put the following code :
```php
// Old line
$entity->set($field, $entity->get($field)['name']);
// New line
$entity->set($field, $path->getFilename());
```

**Comment by davidyell** [comment]
Thanks for the bug report.
