### ISSUE TITLE
the dirty flag is not set on file upload

### ISSUE THREAD

**Issue by danielzzz** [davidyell/CakePHP3-Proffer#122]
hi, it seems that the dirty flag is not set for uploaded fields (I'm checking it in afterSave), which makes post upload file processing a bit complicated.

right now I check getOriginal() value against the current one. but it can easily fail if the newly uploaded file happens to have the same name as the previous one.

I need to know when the file was uploaded to post process the image (apply some filters to it).

thanks, best, dan

**Comment by davidyell** [comment]
If you wanted to apply some filters to the image, you would do that in the ImageTransform class, which gets an instance of the image during the upload process.

You can use the interface provided to create your own ImageTransform class and inject it into the plugin, this will allow you to do any transformation, filtering and changes to the image.

**Comment by davidyell** [comment]
The dirty flag will not be set in `afterSave` because the entity has already been persisted so there is no way to know if the property is dirty or not.

The actual setting of the property before `patchEntity` works okay.
