### ISSUE TITLE
image dir field is not set on create

### ISSUE THREAD

**Issue by danielzzz** [davidyell/CakePHP3-Proffer#125]
hi, I have a strange problem image directory field is not being filled during the entity first save (the image field itself is set correctly)
When I use edit form it does get set.

thanks, dan

**Comment by davidyell** [comment]
So it's not saving the directory (seed) during an add action, but is during an edit? 

So there might be a few potential issues to check for this.

1) That the behaviour is attached the table class and configured properly.
2) The field dir matches the one in your database
3) The field is in the entities `$_accessible` array

**Comment by danielzzz** [comment]
hmm, it seems to be

this is what I have:

protected function _initializeSchema(\Cake\Database\Schema\Table $table)
    {
        $table->columnType('image', 'proffer.file');
        return $table;
    }

//in initialize
$this->addBehavior('Proffer.Proffer', [
                'image' => [
                    'dir'=>'image_dir', 
                    'root' => WWW_ROOT . 'uploads', 
                    'thumbnailMethod' => 'imagick',
                    'thumbnailSizes' => [ // Declare your thumbnails
                            'home' => ['w' => 750, 'h' => 300, 'crop' => true],   // Define the size and prefix of your thumbnails
                            'small' => ['w' => 200, 'h' => 80, 'crop' => true], 
                               // Crop will crop the image as well as resize it
                        ]
                    ]
            ]);


//in validationDefault
$validator
            ->allowEmpty('image');
            
        $validator
            ->allowEmpty('image_dir');

what is strange it does work on edit, but somehow the field image_dir is empty on create...
it there was something wrong it wouldn't work at all would it?

**Comment by davidyell** [comment]
Do any of your validation rules have `->on('create')` ? Which would just run those rules for for create actions? Also did you check your entities `$_accessible` array?

**Comment by danielzzz** [comment]
none of them has ->on('create') but I am using UUIDs for ID and in validator it has:
$validator
            ->add('id', 'valid', ['rule' => 'uuid'])
            ->allowEmpty('id', 'create');

maybe this is the reason?

both image and image_dir fields are in $_accessible array.

thanks!

**Comment by davidyell** [comment]
How very bizarre, I'm not sure what else to try. If you figure it out do let me know, perhaps there is a test case to be added :+1:

**Comment by davidyell** [comment]
Any further progress with this @danielzzz or can I close this ticket?
