### ISSUE TITLE
is there an easy way to delete files and empty the fields?

### ISSUE THREAD

**Issue by danielzzz** [davidyell/CakePHP3-Proffer#127]
Hi, I can upload images and it works fine, but for some objects sometimes I need to delete all the files (+thumbnails if set) and set the fields to null without deleting the whole entity. Is there some easy way to do this with proffer?

thanks, dan

**Comment by davidyell** [comment]
I do it like this in my controller.

```php
// Deleting the cover?
if (isset($this->request->data['delete_cover'])) {
    $this->request->data['image_dir'] = null;
    $this->request->data['cover'] = null;

    $path = new \Proffer\Lib\ProfferPath($this->Leagues, $league, 'cover', $this->Leagues->behaviors()->Proffer->config('cover'));
    $path->deleteFiles($path->getFolder(), true);
}

// patchEntity etc
```

**Comment by danielzzz** [comment]
thanks! 
maybe it would be a good idea to add this this kind action to the behavior directly (either manual to automatic).
for example if $this->request->data['proffer_delete_xx'] is set, then proceed to set xx and xx_dir (from the config) to null and delete the files.
even the delete field could be set in config, maybe..

**Comment by davidyell** [comment]
Relates to #100 #111 #118 #39

**Comment by danielzzz** [comment]
thanks! I understand the scope, but also I feel, deleting files (aca restoring the original db state) could be a natural part of it. anyway, thanks a lot for this plugin and your comments!

**Comment by davidyell** [comment]
I do agree, I've not had enough time to think about a proper solution, which is why I've been reluctant to push out a 1.0.0 release.

**Comment by danielzzz** [comment]
I'd try using some standard name like: "delete_" . $file_field by convention, then delete files if it's set up.

OFFTOPIC: btw, this would be great too, for other fields:
"directory" field: if not set, use $file . "_dir"
root: if not set use /webroot/uploads/
for standard files/images this would reduce the config drastically. 
Now I have to set it up for each field which seems to be a bit of a hassle.

one step forward would be discover fields by name like _img or _file and setting the up automatically.
(I do this on bake level now)
hmm, maybe I should add it as a separate issue?

**Comment by davidyell** [comment]
Well the the [configuration of the directory field](https://github.com/davidyell/CakePHP3-Proffer/blob/master/docs/configuration.md#configuring-the-behaviour-in-your-table) is already taken care of. However it might be beneficial to provide a fallback. If you want to submit a PR with a test for that it would be great. It must not change the current api though, and it's probably also worth putting in a check to ensure the field exists in the db schema.

Plus the [upload path is already set by default to webroot/files](https://github.com/davidyell/CakePHP3-Proffer/blob/master/src/Lib/ProfferPath.php#L43), you only need to configure it if you want to change it.

The problem with using a convention is that it will not fit all the cases for all the people. So a value like that must be configured as well as having a default, which creates more code. The other thing to consider is that it will potentially be different for different files in the same application.

**Comment by danielzzz** [comment]
sure, it's good to have something by convention and then to be able to edit it.
I will check the default config, especially for root.  somehow I couldn't set it globally and ended up having to put it in each field. 
I am quite overloaded with work atm, but I am looking forward to using this plugin and if so I will certainly add some extra features and submit a PR. thanks

**Comment by hervethouzard** [comment]
Hello,

Sorry for coming back on this subject but it's not obvious and it should be written in the documentation.

Bye,
Hervé

**Comment by davidyell** [comment]
Hey @hervethouzard yes good point, I'm always interested in improving the quality of the documentation. 

I'll reopen this issue and add a note to include the code example I've given into the example documentation.

**Comment by hervethouzard** [comment]
Thanks !
