### ISSUE TITLE
Add file information to save in database

### ISSUE THREAD

**Issue by adiramardiani** [davidyell/CakePHP3-Proffer#132]
I look we must add photo_dir field to save directory address, can add optional feature to save in database like :
* photo_size
* photo_type

To save original image size and image type

**Comment by davidyell** [comment]
Currently the plugin doesn't support changing these elements, which means the you will be able to query the file on the filesystem to find out these details.

```php
$pathToFile = '/example/file.jpg';
list($width, $height, $type, $attr) = getimagesize($pathToFile);
```

http://php.net/manual/en/function.getimagesize.php

**Comment by adiramardiani** [comment]
For my case that collected a total of amount of size that is uploaded, I think it would benefit, so from that information could know the total picture that they upload. But it does not matter if you think it will not be profitable. Is there a manual option when uploaded image to include information about the size to the database?

**Comment by davidyell** [comment]
You could probably hook into the event in the plugin to store extra data in the entity before it is persisted.
