### ISSUE TITLE
when the image field is empty I am getting some notices

### ISSUE THREAD

**Issue by danielzzz** [davidyell/CakePHP3-Proffer#134]
When the image field is empty in the form (and it has not been set previously) I am getting the following notices:

Notice (8): Array to string conversion [CORE/src/Database/Statement/PDOStatement.php, line 72]
Notice (8): Array to string conversion [CORE/src/Database/Log/QueryLogger.php, line 78]

**Comment by davidyell** [comment]
What validation have you got against the field? Are you using `allowEmpty()`?

**Comment by danielzzz** [comment]
yes, allowEmpty it is. Shouldn't I?

**Comment by davidyell** [comment]
No, that's fine otherwise you'd not be able to submit the form without adding an upload.

What version are you using? If you're using a version lower than `0.5.0` you need to include the `initializeSchema` in your table class.

**Comment by davidyell** [comment]
[I have a test for this in the testcases](https://github.com/davidyell/CakePHP3-Proffer/blob/master/tests/TestCase/Model/Behavior/ProfferBehaviorTest.php#L301).

I've also tested the scenario you mention and I've been unable to replicate it, sorry.

**Comment by rachid804** [comment]
I had the same error using the last version 0.6.x, and i figured that it's only happen with big images.

**Comment by davidyell** [comment]
It's worth noting that there is a validation rule available in the core framework for validating your upload file sizes, it's usually worth adding this rule with the value matching your maximum allowed upload size in your `php.ini`.

http://api.cakephp.org/3.0/source-class-Cake.Validation.Validation.html#941-961

**Comment by birdy247** [comment]
I am experiencing the same issue.  If I use this

$validator
    ->requirePresence('image', 'create')
    ->allowEmpty('image', 'update');

and edit a record where the image field is present but no file is uploaded.

Array to string conversion [CORE/src/Database/Statement/PDOStatement.php, line 72]

Only way I can get round it is to do something like

            if (isset($this->request->data['photo']) && ($this->request->data['photo']['error'] == 4)) {
                unset($this->request->data['photo']);
            }

before patching the entity

**Comment by davidyell** [comment]
Hmm, I'll take a proper look at this one and see if I can figure out what's happening.

**Comment by birdy247** [comment]
It might be something to do with the fact that when you dont add a file, error:4 which means no_file_uploaded, so the "image" property is still an array.  You will no doubt know more than me though :)

**Comment by davidyell** [comment]
I've tried this, and I can't replicate it.

The use-case of no file is also dealt with in the behaviour already.
https://github.com/davidyell/CakePHP3-Proffer/blob/develop/src/Model/Behavior/ProfferBehavior.php#L58

If anyone has any further information, or can replicate please let me know and I can reopen.

**Comment by dindy** [comment]
Hi! I have the same notice but only when I use a custom validation method. It works when my rules are in validationDefault but not if I rename the validation function and use the 'validate' config when I call patchEntity in a controller. I use v.0.8.1.
