### ISSUE TITLE
Can't get it running

### ISSUE THREAD

**Issue by Saiheng** [davidyell/CakePHP3-Proffer#135]
I am a little bit confused from the example in the docs. 
In the exaplme the fields to store the image-path are named "photo" and "photo_dir",
but in the view there is a formular with the input field named "image", shouldnt this field be named "photo" according to the example?

I tried both ("image" and "photo"), but ether way i can't get it running. If I name it "image" the formular is working but stores nothing to the database. If I name it "photo" (like my field in the database), i get a blank page with the following three notices:
```
Notice (8): Array to string conversion [CORE\src\Database\Statement\PDOStatement.php, line 72]
Notice (8): Array to string conversion [CORE\src\Database\Log\QueryLogger.php, line 78]
Notice (8): Undefined variable: _SESSION [CORE\src\Network\Session.php, line 440]
```
One potential issue is that the Post-Request doesnt seem to recognize my image as a file:
![screen](https://cloud.githubusercontent.com/assets/7591624/9836233/88915eda-5a11-11e5-8366-b686f57d625e.jpg)

Accordingly, I get a new entry to the database with an "Array" inside my "photo" field and an empty "photo_dir" field, the file isn't uploaded to the server.
![array](https://cloud.githubusercontent.com/assets/7591624/9836307/e295d5a2-5a14-11e5-9c84-45c17edee454.jpg)

My formular and my input field both use file-types, here is my template:
```
    <?= $this->Form->create($image, ['type' => 'file']) ?>
    <fieldset>
        <legend><?= __('Add Image') ?></legend>
        <?php
            echo $this->Form->input('photo', ['type' => 'file']);
        ?>
    </fieldset>
    <?= $this->Form->button(__('Submit')) ?>
    <?= $this->Form->end() ?>
```
I also included the nessecary configuartion to my Tables-File (my Model is called "Images"):
```
public function initialize(array $config)
    {
        parent::initialize($config);

        $this->table('images');
        $this->displayField('id');
        $this->primaryKey('id');

        $this->addBehavior('Timestamp');
		
		// Add the behaviour and configure any options you want
		$this->addBehavior('Proffer.Proffer', [
		    'photo' => [    // The name of your upload field
		        'root' => WWW_ROOT . 'files', // Customise the root upload folder here, or omit to use the default
		        'dir' => 'photo_dir',   // The name of the field to store the folder
		        'thumbnailSizes' => [ // Declare your thumbnails
		            'square' => ['w' => 200, 'h' => 200],   // Define the size and prefix of your thumbnails
		            'portrait' => ['w' => 100, 'h' => 300, 'crop' => true],     // Crop will crop the image as well as resize it
		        ],
		        'thumbnailMethod' => 'imagick'  // Options are Imagick, Gd or Gmagick
		    ]
		]);
    }

    /**
     * Default validation rules.
     *
     * @param \Cake\Validation\Validator $validator Validator instance.
     * @return \Cake\Validation\Validator
     */
    public function validationDefault(Validator $validator)
    {
        $validator
            ->add('id', 'valid', ['rule' => 'numeric'])
            ->allowEmpty('id', 'create');

        $validator
            ->allowEmpty('photo');

        $validator
            ->allowEmpty('photo_dir');

        return $validator;
    }
```
I am new to cakephp so maybe I'm just missing a simple point. I would be thankful for any hints. I am using proffer v.0.4

**Comment by davidyell** [comment]
So there are two main issues you're encountering.

The first is that the name of the field in the example is irrelevant. You need to make sure that the naming is consistent in your application, following your database. So if you've called the fields 'photo' and 'photo_dir' in your database, then that's what you should be using across all your forms and behaviour configuration.

The second issue, the reason why it's saving 'Array' to the database is that you've forgotten to include the `initializeSchema` method in your table class. You can see this method in the [older version of the docs](https://github.com/davidyell/CakePHP3-Proffer/blob/v0.4.2/docs/configuration.md#configuring-the-behaviour-in-your-table). Although you'd be better off upgrading to `0.5.0` to avoid this step.

It's a good suggestion to update the documentation, to make the examples consistent. I'll take care of that.
