### ISSUE TITLE
Multiple upload

### ISSUE THREAD

**Issue by ironbone** [davidyell/CakePHP3-Proffer#140]
Is it possible to use this plug-in in order to upload multiple files at ones and save the filenames (with the "owner" id) in a separated table

Or juts upload one by one and save multiple files in a separate table?

**Comment by davidyell** [comment]
Yes it is possible to achieve this. There are two possible use-cases here.

**Uploading multiple files to the same table class.** 
There is [an example included in the documentation](https://github.com/davidyell/CakePHP3-Proffer/blob/master/docs/examples.md#uploading-multiple-related-images).

**Uploading multiple images at the same time**
[There is a test case for it](https://github.com/davidyell/CakePHP3-Proffer/blob/master/tests/TestCase/Model/Behavior/ProfferBehaviorTest.php#L795-L867).

I should add some documentation for uploading multiple images to the same table class.
