### ISSUE TITLE
Info for associating many images to one item

### ISSUE THREAD

**Issue by vnt** [davidyell/CakePHP3-Proffer#148]
Hello,
congratulations for the project.
Your plugin can associate many images to an item?
For more information:
http://cakephp-upload.readthedocs.org/en/latest/polymorphic.html
Thanks a lot and sorry for my english.

**Comment by davidyell** [comment]
https://github.com/davidyell/CakePHP3-Proffer/blob/master/docs/examples.md#uploading-multiple-related-images
