### ISSUE TITLE
after updating to cake 3.1.4 I getting errors about missing files

### ISSUE THREAD

**Issue by danielzzz** [davidyell/CakePHP3-Proffer#153]
hi, I updated cake to 3.1.4 and also proffer with composer
Updating davidyell/proffer dev-master (8604cac => b4e3e23)
Checking out b4e3e2364bba030a6dabaa454a3cbe63d1026b5e

but now I am getting:
Warning (2): include(/home/vagrant/www/bc/vendor/davidyell/proffer/config/bootstrap.php): failed to open stream: No such file or directory [CORE/src/Core/Plugin.php, line 388]
Warning (2): include() [function.include]: Failed opening '/home/vagrant/www/bc/vendor/davidyell/proffer/config/bootstrap.php' for inclusion (include_path='.:/usr/share/php:/usr/share/pear') [CORE/src/Core/Plugin.php, line 388]

for some reason the plugin bootstrap file is missing?

please advice, thanks!
dan

**Comment by davidyell** [comment]
Please see the upgrading docs, specifically for `0.5.0`

https://github.com/davidyell/CakePHP3-Proffer/blob/master/docs/upgrading.md#050
