### ISSUE TITLE
resize the base image

### ISSUE THREAD

**Issue by danielzzz** [davidyell/CakePHP3-Proffer#154]
hi, I have one doubt - I've seen I can name and resize additional thumbnails:
'thumbnailSizes' => [ // Declare your thumbnails
            'square' => [   // Define the prefix of your thumbnail
                'w' => 200, // Width
                'h' => 200, // Height
                'crop' => true  // Crop will crop the image as well as resize it
                'jpeg_quality'  => 100,
                'png_compression_level' => 9
            ],

but is it possible to resize the original image without creating extra thumbnails? how to configure that?

thanks, dan

**Comment by davidyell** [comment]
No, this is not possible.

There are a number of reasons for this.
1. The original image is still uploaded, so it can be referenced in markup as normal.
2. If you want to resize an image you make a thumbnail.
