### ISSUE TITLE
Upload pictures and PDF

### ISSUE THREAD

**Issue by hervethouzard** [davidyell/CakePHP3-Proffer#156]
Hello,

I don't know if it's a bug or just that the plugin was not made for this but on a form I have 6 fields for pictures and one field for a PDF.

My model's table was modified to add the PDF, the file is uploaded when I submit the form, the database field containing the document's title is filed but not the field with the file's location (the 'dir' field in the documentation).

Is there a way to fill the "dir" field?

Bye

**Comment by hervethouzard** [comment]
Hello,

Sorry there's no bug, I just had a problem with Cake's model cache...
Sorry.

**Comment by davidyell** [comment]
Glad you figured it out!
