### ISSUE TITLE
I have imagine 0.6.3, won't install as it requires imagine 0.6.2

### ISSUE THREAD

**Issue by daviddebeer** [davidyell/CakePHP3-Proffer#157]
I have been trying to install proffer, unfortunately I am getting an error/problem that says I cannot install it as it requires imagine 0.6.2 but I already have imagine  0.6.3... Do I need to remove imagine and reinstall with the lower version?

**Comment by daviddebeer** [comment]
Reverted to an earlier version of my software before installing imagine and then installed it successfully (I had previously installed burzum/cakephp-imagine-plugin, which had created the clash)

**Comment by davidyell** [comment]
Yep, this is a problem with Composer. If you are using two different packages which depend on different versions of the same library they will clash.

Unfortunately I have no idea how to get around it. I'm glad you found out which packages were clashing though.

A quick Google turned up a ticket discussing this issue in the Composer issues.
https://github.com/composer/composer/issues/2609

**Comment by davidyell** [comment]
On second thoughts, I'll re-open this as a reminder to upgrade to Imagine `0.6.3`

**Comment by daviddebeer** [comment]
Thank you for your prompt response.

 

Don’t know if you will receive this, and I am sure you get lots of what you consider silly questions so I apologise for this but:

 

I am trying to get the “UploadFilenameListener” example that you give to work. I am very new to cake so I am sure that I am making an incredibly stupid mistake but I am getting a “Class 'App\Model\Table\App\Event\LogFilenameListener' not found” error.

 

I have saved the UploadFilenameListener.php file in the App/src/Event folder

I have copied it exactly as it is in your example.

 

My models table file starts like this:

class AgentsTable extends Table

{

 

                /**

                * Initialize method

                *

                * @param array $config The configuration for the Table.

                * @return void

                */

                public function initialize(array $config)

                {

                                parent::initialize($config);

                                

                                $listener = new App\Event\UploadFilenameListener();

                                $this->eventManager()->on($listener);

…etc etc

                }

}

 

David de Beer

**Comment by davidyell** [comment]
You're welcome. 

If you have other questions, please open another issue, rather than confusing things by asking different questions in the same ticket, thanks.
