### ISSUE TITLE
Error in example "UploadFilenameListener.md"

### ISSUE THREAD

**Issue by ranferi** [davidyell/CakePHP3-Proffer#161]
Hi David, so when I try to upload, an error show up:
> 2016-01-21 18:38:59 Notice: Notice (8): Indirect modification of overloaded element of App\Model\Entity\Imagen has no effect in [...\src\Event\UploadFilenameListener.php, line 57]

So I checked and I think this line:
``` php
$event->subject()['image']['name'] = $newFilename;
```
should be:
``` php
$event->subject('image')['name'] = $newFilename; 
```
After I made this change it worked for me.

**Comment by davidyell** [comment]
Thanks, I'll get the example updated.
