### ISSUE TITLE
cleanup task deletes all files when model has Multiple proffer columns

### ISSUE THREAD

**Issue by tkawaji** [davidyell/CakePHP3-Proffer#163]
When model has multiple proffer column, cleanup task deletes all folders.
I think it is because in cleanup method,
there is no "continue;" when folder name and column name does not match.

May I fix it in new PR?

**Comment by davidyell** [comment]
Relates to #81 

Sure, if you have the fix to hand a PR would be great. Don't forget a test for it, if at all possible.

**Comment by tkawaji** [comment]
Is there any testcases for Shell?
I can test it manually in my project, but It's hard to make testcase from scratch.

**Comment by davidyell** [comment]
Closed as the PR is merged.

**Comment by tkawaji** [comment]
Thank you for merging!
