### ISSUE TITLE
what would be the best way to handle images not uploaded via a form

### ISSUE THREAD

**Issue by danielzzz** [davidyell/CakePHP3-Proffer#170]
hi, I have one question:

I need to import a large number of entities from a csv and related images are already on the server, so they are not being uploaded, just copied over.
What would be the best way to handle it, so I will end up with the same directories as proffer would have created?

thanks, dan

**Comment by davidyell** [comment]
Personally I would make a shell, and use that to import.

Then I would load rows from the csv in a loop and build an entity, then I'd build the `$_FILES` array in the request data and then merge that into a new entity. Then you should be able to save the entity and it'll run as normal.
