### ISSUE TITLE
How do I upload images on another server?

### ISSUE THREAD

**Issue by vnt** [davidyell/CakePHP3-Proffer#171]
Hi Devideyell,
I have created a separate backend and frontend applications.

backend
-webroot
-src

frontend
-webroot
-src

img
-directory a
-directory b

How do I upload images on another server and make them available for the backend and the frontend?

Thanks a lot,
D.

**Comment by davidyell** [comment]
So you want to upload an image from one application into another?

The plugin does not support this functionality, sorry.
