### ISSUE TITLE
Encoding issue with German umlauts in the filename

### ISSUE THREAD

**Issue by hasentopf** [davidyell/CakePHP3-Proffer#175]
When I upload a file with German umlauts in the filename the image value in the database field got strangely encoded.
e.g. "Nürburgring.jpg" -> "Nu?rburgring.jpg"

**Comment by davidyell** [comment]
Ah, perhaps it needs some transliteration happening. Do German language operating systems support storing files with accented characters?

I guess a more global solution would be to transliterate the characters, but then it might end up with a filename which is not obvious.

**Comment by hasentopf** [comment]
Hi David. Thank you for the quick response.
I'm using Mac OS X in English - storing files with accented characters is no problem.

I think it's not a file system problem. Storing the filename in the database fails.
The uploaded file is correct "Nürburgring.jpg" but the datebase entry is "Nu?rburgring.jpg".

**Comment by davidyell** [comment]
Sounds like your database table encoding might not be UTF-8 then.

**Comment by hasentopf** [comment]
Jap... it was a table encoding problem... Thank you for the tip!

**Comment by davidyell** [comment]
Glad you got it sorted :tada:
