### ISSUE TITLE
notice error PDOStatement 

### ISSUE THREAD

**Issue by scallacs** [davidyell/CakePHP3-Proffer#176]
CakePHP 3.1.12 and Proffer 0.6.3. 

The file upload works but there is a notice error:
Notice Error: Array to string conversion in [CORE/src/Database/Statement/PDOStatement.php, line 72]

Upload is coming from an android app:
Content-Disposition: form-data; name="photo"; filename="OOO.jpg"
Content-Type: image/jpeg
Content-Length: 424508

Any ideas ?

**Comment by davidyell** [comment]
My first initial thought is that it's the Marshaller not changing the data type map properly.

Although the source shows this as a problem with bindValue, which would point to the marshaller again, trying to put an array value into a string field. Which would mean that it's trying to insert the `$_FILES` array into the db.

This should be taken care of by [the custom data type](https://github.com/davidyell/CakePHP3-Proffer/blob/master/src/Database/Type/FileType.php), which is [automatically mapped in the behavior](https://github.com/davidyell/CakePHP3-Proffer/blob/master/src/Model/Behavior/ProfferBehavior.php#L36).

[This can also happen if the form field isn't `'type' => 'file'`](https://github.com/davidyell/CakePHP3-Proffer/blob/master/docs/faq.md#file-name-is-written-to-the-database-as-array).

**Comment by sereskrisztian** [comment]
I had the same problem today. It seemed to be the insufficient value of 'upload_max_filesize', I just had to increase it.

**Comment by scallacs** [comment]
I finally found where this error was coming from. 
I used the following application rule where `photo `is an array! 
`$rules->add($rules->isUnique(['photo', 'photo_dir']));`

Thanks!
