### ISSUE TITLE
a possible bug in paths (upload vs shell processing)

### ISSUE THREAD

**Issue by danielzzz** [davidyell/CakePHP3-Proffer#181]
hi, I think I might have discovered a possible inconsistence in path management between the upload and shell processing. 

I have a table called boat_photos. When I upload files from within the form, the path created is /boatphotos/[UUID]/photo/filename.jpg 

But when I try to process it with the "generate" shell task it complains about missing boat_photos/[UUID]/photo/filename.jpg

the difference being boatphotos vs boat_photos

thanks, dan

**Comment by davidyell** [comment]
Ooh, good spot, thanks! If you're confident enough with a fix, please feel free to submit a pull request with a fix to the `develop` branch, and I can get that merged in.

**Comment by davidyell** [comment]
I can't replicate this.

I create a table called `mailing_lists` with a `photo` field, and then uploaded an image. It's path is `/webroot/files/mailinglists/photo/b18a9963-1f82-4ad0-8c7d-7a21c2b3dbde`.

Then I ran the shell and it worked fine

```bash
Welcome to CakePHP v3.2.10 Console
---------------------------------------------------------------
App : src
Path: /home/neon/Sites/cakefest2016/src/
PHP : 7.0.7-4+deb.sury.org~trusty+1
---------------------------------------------------------------
Thumbnails regenerated for MailingLists cakfest.png

Completed
```
