### ISSUE TITLE
Wrong dimensions for few thumnails

### ISSUE THREAD

**Issue by dario86** [davidyell/CakePHP3-Proffer#183]
Hi. I have this configuration

```
$this->addBehavior('Proffer.Proffer', [
    'logo' => [
        'root' => WWW_ROOT . 'upload',
        'dir' => 'logo_dir',
        'thumbnailSizes' => [
            'big' => ['w' => 220, 'h' => 140],
            'thumb' => ['w' => 150, 'h' => 95],
        ],
        'thumbnailMethod' => 'imagick',
    ],
]);
```
I uploaded an image of 111x26 pixels, but thumnails are created without change dimensions (i tried with `crop => true` but i get error 
`[Imagine\Exception\OutOfBoundsException] Crop coordinates must start at minimum 0, 0 position from top left corner, crop height and width must be positive integers and must not exceed the current image borders`)

An image with 1040x791 pixel has the `thumb` version with 125x95 and `big` with 184x140

**Comment by davidyell** [comment]
Yeah, I've hit this too, the resize code does a best fit without changing the aspect ratio. It needs updating.  Relates to #124

**Comment by dario86** [comment]
With this?

```
protected function thumbnailScale(ImageInterface $image, $width, $height)
    {
        $im = new Imagick($image->metadata()['filepath']);
        $im->resizeImage($width, $height, imagick::FILTER_LANCZOS, 1);
        return $im;
    }
```

**Comment by davidyell** [comment]
I'm going to close this one in favour of #124
