### ISSUE TITLE
Remove file field on edit form

### ISSUE THREAD

**Issue by florianMo** [davidyell/CakePHP3-Proffer#185]
I have an entity with several file fields, and on my entity edit form I need to be able to remove a file (i.e empty a file field). If I leave a file input empty on the edit form and submit, the field stays as it was, which is just fine, but I'd like to add a link to remove the file (for the moment, all I can do is replace the existing file).

I started thinking about an ajax action on my controller which empty a given field. Then I can add a "trash link" for each file field on the edit form.

Is there a better option / approach ?
Thank you

EDIT
Sorry I just saw [this](https://github.com/davidyell/CakePHP3-Proffer/blob/master/docs/examples.md#deleting-images-but-preserving-data), which seems to answer my question.

**Comment by davidyell** [comment]
Yep, was going to link to that, glad you found it.
