### ISSUE TITLE
Remove associated files

### ISSUE THREAD

**Issue by edsonmgoz** [davidyell/CakePHP3-Proffer#187]
This plugin is amazing. I have a problem deleting related images, the relationship I have is **hasMany ()**, **belongsTo ()** and when I remove images from the associated table do not realize, what I did was eliminate **$path-> deletefiles** and cycle foreach of the images but does not seem very optimal. Please let me know if there is any solution for this. 

Thank you very much.

**Comment by davidyell** [comment]
Seem odd that you should have to delete files manually in your code, as the `afterDelete` method should deal with this for you.

https://github.com/davidyell/CakePHP3-Proffer/blob/master/src/Model/Behavior/ProfferBehavior.php#L133-L166

**Comment by edsonmgoz** [comment]
I only happens when I want to remove associated images :-( , I will check the code. Thank you very much for your attention.

**Comment by mokiwaa** [comment]
Can you help me on  how I implement the afterDelete to remove associated uploads files as you suggested on your comment above. I have the same problem as edsonmgoz, but I dont know how to do, to use the afterDelete callback.

**Comment by davidyell** [comment]
The `afterDelete` method I mention is part of the plugin.

**Comment by mokiwaa** [comment]
Yes I know but... Taking your exemple with Post, when I call the delete action of Post, how can I call the afterdelete method to delete the associate upoload files. In my project I have Post and image
with relation Post hasMany Images and Images belongsTo Post. the proffer plugin is in Images Model.
In the delete action of post, all the images are deleted, but not the files... and I'm lost beacause I dont know how to call the afterDelete method of the proffer plugin in Post controller... :S

**Comment by davidyell** [comment]
Sounds like you do not have `cascadeCallbacks` set in your Table relationships, as `afterDelete` is called automatically upon deletion.

**Comment by mokiwaa** [comment]
Ohh... I'm feeling  stupid right now... Many thanks for your help.. ;)

**Comment by davidyell** [comment]
Resolved in the 0.8.1 release.
