### ISSUE TITLE
Deleting multiple images but preserving data

### ISSUE THREAD

**Issue by vnt** [davidyell/CakePHP3-Proffer#189]
Hi,
How do I deleting multiple images but preserving data?

**Comment by davidyell** [comment]
The plugin does not provide this functionality. This is something you'd need to do yourself in your controllers delete method.

The plugin works by hooking the `afterDelete` callback when deleting an entity to remove the related uploads.

The `ProfferPath` class provides methods which you can use to clear uploads from your system.

```php
// Create a new path instance using the current table, the entity which the uploads are for, and the configured upload field, along with any settings for that field as configured in the behaviour.
$profferPath = new Proffer\Lib\ProfferPath($table, $entity, $field, $fieldSettings);
// Use the path class to delete all the files and the containing folder.
$profferPath->deleteFiles($profferPath->getFolder(), true);
```
