### ISSUE TITLE
How do I save the full path ?

### ISSUE THREAD

**Issue by alexsmonte** [davidyell/CakePHP3-Proffer#198]
how do I not have it
files/posts/image_featured/2016/07
and have it
/files/2016/07

How do I save the full path along with the image in the photo field?

![captura de tela de 2016-07-09 00 16 14](https://cloud.githubusercontent.com/assets/1400348/16706010/652aa0a6-456a-11e6-9a51-5dd51b7e7dbc.png)

**Comment by davidyell** [comment]
You can use a listener for this as detailed in the documentation.

https://github.com/davidyell/CakePHP3-Proffer/blob/master/docs/customisation.md#customising-upload-file-names-and-paths
