### ISSUE TITLE
Is there a method to get the proportionate thumbnails?

### ISSUE THREAD

**Issue by vnt** [davidyell/CakePHP3-Proffer#199]
Is there a method to get the proportionate thumbnails?

**Comment by davidyell** [comment]
I'm sorry, I don't understand the question.

What do you mean?

**Comment by michelpeters** [comment]
I'm looking for the same, as I mentioned in an earlier issue #124 . I saw you closed another ticket referring to thumbnails/aspectratio and pointed to the #124 one. Couple minutes ago I tried the  'fit' and 'crop' options in the thumbnail config, but could not get what I wanted.

So what do I/we want/like? Basically the functionality thats described in the issue and referring to how UploadPack worked in CakePHP 2. Maybe I should look into it myself and see if I can help. 

Do you see any problem in "looking at the code from UploadPack, integrate/implement that into the thumbnail generation code in Proffer -> win" ? Would it be hard/easy, given how Proffer works (and you want it to work)?

**Comment by davidyell** [comment]
Please update to `0.7.0` which implements Intervention Image which solves this issue.

**Comment by davidyell** [comment]
If there are no further updates, I'll close this to keep things tidy.
