### ISSUE TITLE
Multiple Image Upload Single Field

### ISSUE THREAD

**Issue by spacebiscuit** [davidyell/CakePHP3-Proffer#207]
Hi,

Does this plugin support multiple image uploads via a single field. I see that you have an example for multiple upload fields but not html5 multiple images on a single field.

TY.

**Comment by davidyell** [comment]
No it doesn't. I wasn't aware this was possible, sorry.

**Comment by spacebiscuit** [comment]
Take a look at html5 - multiple attribute.

Thanks.

**Comment by davidyell** [comment]
On second thoughts, I'll reopen this as an enhancement.

**Comment by spacebiscuit** [comment]
Hi I'm not sure this is actually possible. I have been customising the plugin all day and although I can get it to work for multiple files on a single upload field, this then breaks the single file upload. My approach was to loop the array of objects that the multiple attribute produces. This works nicely but the issue is that there is nothing to loop for a single file upload, so I tried to move the single array into a 0 index to mimic the structure of the multiple file object but of course once I do this the object in not a valid instance of Cake\ORM\Entity so the new ProfferPath fails.

I'm not sure if there is a simpler way of doing this, likely this is just a bit beyond me I would imagine.

**Comment by davidyell** [comment]
My first thought is that the upload and processing of a single file works just fine. So the only thing which really needs to happen is checking if the submitted `$_FILES` array is a multiple or not. If it isn't, then the code can run as normal, and if it is a multiple, just call the existing code in a loop.

However I will qualify this by saying that I haven't looked at how the multiple file type input creates data in the request yet, so I am making an assumption here.

**Comment by spacebiscuit** [comment]
Agreed, I thought it would be a case of just looping the request data but consider the difference between the two:

Single file:

```
object(App\Model\Entity\Listing) {

	'title' => 'test',
	'vehicle_id' => (int) 1,
	'photo' => [
		'name' => 'quiz.jpg',
		'type' => 'image/jpeg',
		'tmp_name' => 'C:\Program Files\WAMP\tmp\php5CF.tmp',
		'error' => (int) 0,
		'size' => (int) 4094
	],
```

Mutliple:

```
object(App\Model\Entity\Listing) {

	'title' => 'test',
	'vehicle_id' => (int) 1,
	'photos' => [
		(int) 0 => object(App\Model\Entity\Photo) {

			'name' => 'podcast.png',
			'type' => 'image/png',
			'tmp_name' => 'C:\Program Files\WAMP\tmp\phpACFF.tmp',
			'error' => (int) 0,
			'size' => '48411',
			'[new]' => true,
			'[accessible]' => [
				'*' => true
			],
			'[dirty]' => [
				'name' => true,
				'type' => true,
				'tmp_name' => true,
				'error' => true,
				'size' => true
			],
			'[original]' => [],
			'[virtual]' => [],
			'[errors]' => [],
			'[invalid]' => [],
			'[repository]' => 'Photos'
		
		},
		(int) 1 => object(App\Model\Entity\Photo) {

			'name' => 'quiz.jpg',
			'type' => 'image/jpeg',
			'tmp_name' => 'C:\Program Files\WAMP\tmp\phpAD00.tmp',
			'error' => (int) 0,
			'size' => '4094',
			'[new]' => true,
			'[accessible]' => [
				'*' => true
			],
			'[dirty]' => [
				'name' => true,
				'type' => true,
				'tmp_name' => true,
				'error' => true,
				'size' => true
			],
			'[original]' => [],
			'[virtual]' => [],
			'[errors]' => [],
			'[invalid]' => [],
			'[repository]' => 'Photos'
		
		}
	],
```

The multiple upload objects is an array of objects which I think is due to the patchEntity called in my controller. If I debug the request **_before_** this is called then I do see an array of arrays which would be ideal.

Any thoughts?

**Comment by spacebiscuit** [comment]
I've managed to get this working, I will create the pull request tomorrow!

**Comment by davidyell** [comment]
Resolved, functionality has been developed and deployed now in release 0.8.1
