### ISSUE TITLE
Feature requiring: Position of the crop

### ISSUE THREAD

**Issue by danielfpedro** [davidyell/CakePHP3-Proffer#212]
I think the only thing that is missing is this plugin to be perfect is a a feature to set the position of the crop:

Something like that:

        'thumbnailSizes' => [ // Declare your thumbnails
            'square' => [   // Define the prefix of your thumbnail
                'w' => 200, // Width
                'h' => 200, // Height
                cropPosition' => ['left', 'top'],
                'jpeg_quality'  => 100
            ],
        ],

**Comment by davidyell** [comment]
The plugin already does this, though the Intervention Image library. You'll have to use the `custom` method, but then you can call any Intervention Image method.

Such as crop, http://image.intervention.io/api/crop which takes X and Y coords.
