### ISSUE TITLE
image not uploading with associated model

### ISSUE THREAD

**Issue by anujsharma9196** [davidyell/CakePHP3-Proffer#217]
I have two models `Startups` and `StartupLogos` and their association is 
```
Startups->hasMany('StartupLogos', [
    'foreignKey' => 'startup_id'
]);
StartupLogos->belongsTo('Startups', [
   'foreignKey' => 'startup_id'
]);
```

I have initialized `Proffer` plugin in `StartupLogosTable.php`
```
$this->addBehavior('Proffer.Proffer', [
      'logo' => [
           'root' => WWW_ROOT . 'files',
            'dir' => 'dir',
            'thumbnailSizes' => [
                'thumbnail' => [
                    'w' => 150,
                    'h' => 150,
                    'fit' => true,
                    'jpeg_quality' => 100
                ],
            ],
            'thumbnailMethod' => 'gd',
        ]
    ]);
```
and validation rule as
```
 $validator->provider('proffer', 'Proffer\Model\Validation\ProfferRules');
    $validator
        ->add('logo', 'proffer', [
            'rule' => [
                'dimensions', [
                    'min' => ['w' => 100, 'h' => 100],
                    'max' => ['w' => 1000, 'h' => 1000]
                ]
            ],
            'message' => 'Image must be 100x100 to 1000x1000',
            'provider' => 'proffer'
        ])
        ->notEmpty('logo');
```

and trying to upload image along with new startup record
```
echo $this->Form->create($startup, ['type' => 'file']);
echo $this->Form->input('title');
echo $this->Form->input('startup_logos.logo', ['type' => 'file']);
echo $this->Form->submit();
echo $this->Form->end();
```

This is creating a new record in `StartupLogos` but image file selected is not uploading.

Uploading image without startup association is working fine. Like, below form is working
```
echo $this->Form->create($startup_logos, ['type' => 'file']);
echo $this->Form->input('startup_id', ['options' => $startups]);
echo $this->Form->input('logo', ['type' => 'file']);
echo $this->Form->submit();
echo $this->Form->end();
```

**Comment by davidyell** [comment]
You haven't made your upload field into an array, which is why your files are not being uploaded.

Your input field should be something like this, 
```php
echo $this->Form->input('startup_logos.logo[]', ['type' => 'file']);
```

This will then enable you to upload either 1 or many files depending on if you want to use the HTML5 `multiple` file input attribute.

**Comment by anujsharma9196** [comment]
```
echo $this->Form->input('startup_logos.logo[]', ['type' => 'file']);
```
this line has no effect. I changed it to 
```
echo $this->Form->input('startup_logos.0.logo', ['type' => 'file']);
```
and it's working

**Comment by kajko1973** [comment]
Here's what's working for me. I have a Galleries table that hasMany Photos, and Photos table has a photo field.
In gallery edit form:
<?= $this->Form->input('photos[].photo', ['type' => 'file', 'multiple' => true, 'label' => 'Files to upload']) ?>
This way everything is like it should, files are saved and records for them added to table. Hope it helps.

**Comment by davidyell** [comment]
If you'd like to see an example @anujsharma9196 I have an example app repository which has all this implemented already. You can find it here, https://github.com/davidyell/CakePHP3-Proffer-Example

I'll close this for the meantime as it seems you've resolved your issue, and someone else has kindly confirmed it's working for them. If you still have problems, please let me know.
