### ISSUE TITLE
Generated thumbnails are rotated

### ISSUE THREAD

**Issue by jaybuddy** [davidyell/CakePHP3-Proffer#224]
Using the following configuration:

```$this->addBehavior('Proffer.Proffer', [
            'photo' => [    // The name of your upload field
                'root' => WWW_ROOT . 'files', // Customise the root upload folder here, or omit to use the default
                'dir' => 'photo_dir',   // The name of the field to store the folder
                'thumbnailSizes' => [ // Declare your thumbnails
                    'square' => [   // Define the prefix of your thumbnail
                        'w' => 100, // Width
                        'h' => 100, // Height
                    ]
                ],
                'thumbnailMethod' => 'gd'
            ]
        ]);
```

If the image is portrait, the thumbnail that is generated is rotated -90 degrees. 
if the image is landscape, it is not rotated.

![20150823_162336](https://cloud.githubusercontent.com/assets/6664783/23959606/d929bb60-0962-11e7-9405-6ca1d7e5ebe6.jpg)

![square_20150823_162336](https://cloud.githubusercontent.com/assets/6664783/23959626/e16e2f0e-0962-11e7-930b-cd6be8b9067c.jpg)

Is there a known fix for this?

**Comment by jaybuddy** [comment]
nevermind i came up with a solution, not pretty cuz i have to modify the plugin but by adding chaining the orientate() method to $image->fit() it preserves the orientation

**Comment by jaybuddy** [comment]
Stoked to see this got added to the plugin. Cheers!

**Comment by davidyell** [comment]
@jaybuddy Yep, I pushed a new release with code which someone kindly added in a pull request.
