### ISSUE TITLE
how could I upload file without maintain original file?

### ISSUE THREAD

**Issue by vnt** [davidyell/CakePHP3-Proffer#231]
Hi,
how could I upload file without maintain original file?
I would only thumbnails.
Thanks in advance
Best regards
D.

**Comment by davidyell** [comment]
I would bind the `Proffer.afterCreateImage` event, and then use that to know that the thumbnails have been created, then I would manually delete the source image.

**Comment by davidyell** [comment]
Did you manage to make any progress with this @vnt ?

**Comment by davidyell** [comment]
I'm going to close this one now, as it's nearly a year old.
