### ISSUE TITLE
When uploading files file path is webroot\files\teams\photo\webroot\files\Teams\photo

### ISSUE THREAD

**Issue by FritsOosterhoff** [davidyell/CakePHP3-Proffer#234]
Hi guys, 

i have been having this problem for a while now, whenever i upload a file several unnecessary folders are created.

`webroot\files\teams\photo\webroot\files\Teams\photo`

this is my TeamsTable

                           $this->addBehavior('Proffer.Proffer', [
      'photo' => [
    		// 'root' => 'files',
    		'dir' => 'photo_dir',
    		'thumbnailSizes' => [ 
    			'xvga' => [	
    				'w' => 1024,	
    				'h' => 768,	
    				'jpeg_quality'	=> 100
    			],
    			'vga' => [		// Define a second thumbnail
    				'w' => 640,
    				'h' => 480
    			],
          'thumb' => [
            'w' => 80,
            'h' => 80
          ]

    		],
    		'thumbnailMethod' => 'gd'	// Options are Imagick or Gd
    	]
    ]);

Is it a stupid mistake? I just dont know.

Thanks for your time!

**Comment by davidyell** [comment]
Looks okay to me 👍

**Comment by FritsOosterhoff** [comment]
In the end i got it fixed, ended up using your custom path listener, resetting the paths to what i needed. Not too sure why the extra folders were created..
