### ISSUE TITLE
Can I use this plugin to upload video files?

### ISSUE THREAD

**Issue by anuj9196** [davidyell/CakePHP3-Proffer#237]
- [x]  Question

I have to upload video files in my application but couldn't find any video uploading plugin.

Can I use this plugin to upload video files same as it is uploading image files?

**Comment by davidyell** [comment]
Yes, I don't see why it wouldn't work just fine.

You will be subject to a few constraints though, from your php.ini.

- [post_max_size](http://php.net/manual/en/ini.core.php#ini.post-max-size)
- [upload_max_filesize](http://php.net/manual/en/ini.core.php#ini.upload-max-filesize)

You'll also want to think about if the upload is interrupted, if it's a large file, how would you resume. You may also need to check the validation to ensure that the extensions work.

Let me know how you get on.
