### ISSUE TITLE
Error during PHPUnit test

### ISSUE THREAD

**Issue by LeoGil** [davidyell/CakePHP3-Proffer#242]
During a PHPUnit test I got an error that during the test he is trying to read the table schema, but the test routine of CakePHP doesn't create the table giving me this error: 

>  Exception: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'pnc_test.items' doesn't exist in [/home/Leonardo/public_html/pncDB/vendor/cakephp/cakephp/src/Database/Schema/Collection.php, line 131]

When I comment the addBehavior of proffer  everything works:

`$this->addBehavior('Proffer.Proffer', [
            'photo' => [ // The name of your upload field
                'root' => WWW_ROOT . 'files', // Customise the root upload folder here, or omit to use the default
                'dir' => 'photo_dir', // The name of the field to store the folder
                'thumbnailSizes' => [ // Declare your thumbnails
                    'square' => [ // Define the prefix of your thumbnail
                        'w' => 200, // Width
                        'h' => 200, // Height
                        'crop' => true,
                        //'jpeg_quality' => 100
                    ],
                    'bpindex' => [ // Define the prefix of your thumbnail
                        'w' => 48, // Width
                        'h' => 30, // Height
                        'fit' => true,
                        //'jpeg_quality' => 100
                    ]
                ],
                'thumbnailMethod' => 'gd' // Options are Imagick or Gd
            ]
        ]);`

**Comment by davidyell** [comment]
Sorry, I don't understand. Please can you give some more context. The unit tests of the plugin pass just fine.

**Comment by davidyell** [comment]
If anything, it seems that TravisCI isn't working as expected, so perhaps it's related to this.
