### ISSUE TITLE
UnexpectedValueException - coming up when using composer

### ISSUE THREAD

**Issue by sybershocknetworks** [davidyell/CakePHP3-Proffer#244]
I am trying to install the library using 

`composer require 'davidyell/proffer:^0.8.2'`

I immediately get:

```
 [UnexpectedValueException]
  Could not parse version constraint 0.8.2': Invalid version string "0.8.2'"
```

What could be wrong?

Thanks!

**Comment by davidyell** [comment]
[Please see the documentation for the correct version constraint](https://github.com/davidyell/CakePHP3-Proffer/blob/master/docs/installation.md#getting-the-plugin).

Alternatively, [please check the Composer documentation](https://getcomposer.org/doc/articles/versions.md).

**Comment by sybershocknetworks** [comment]
I have checked the version. 0.8.2, I am still not able to run it on composer. Let me know!
