### ISSUE TITLE
Blank row created when no image is selected

### ISSUE THREAD

**Issue by anuj9196** [davidyell/CakePHP3-Proffer#245]
I am using this plugin to upload multiple associated images like
```
<?= $this->Form->control('associations.0.photo') ?>
<?= $this->Form->control('associations.1.photo') ?>
<?= $this->Form->control('associations.2.photo') ?>
```
This field are optional and not required that user will select image or select all images.
When there is no file selected, a blank row is created with `NULL` value.

**How can I prevent creating `NULL` row when no image is selected or few images are not selected?**

**Comment by davidyell** [comment]
Two options here,

Firstly, you can loop through the post data to ensure the fields are not empty and unset any which are from your post data.

Secondly, you could use an HTML5 multiple file input field. [As shown in the example application](https://github.com/davidyell/CakePHP3-Proffer-Example/blob/master/src/Template/Posts/edit.ctp#L24), or [the documentation](https://github.com/davidyell/CakePHP3-Proffer/blob/master/docs/configuration.md#uploading-multiple-files).
