### ISSUE TITLE
Remove "afterDelete" hook

### ISSUE THREAD

**Issue by elriri35** [davidyell/CakePHP3-Proffer#246]
Hi !

I would like delete an entity without unlink files, how can i do it ? 

Thanks in advance

**Comment by davidyell** [comment]
Two potential options.

1) Remove the behaviour from the Table class before performing the delete.
```php
$this->behaviors()->unload('Proffer');
```

2) Copy the file somewhere before performing the delete.
```php
copy('/foo/example.pdf', '/bar/example.pdf');
```
