### ISSUE TITLE
Cambiar el path

### ISSUE THREAD

**Issue by mikidiaz** [davidyell/CakePHP3-Proffer#249]
Como podría cambiar el path que viene por defecto para que me lo guarde en una carpeta específica.
Saludos y gracias.

**Comment by davidyell** [comment]
You can change the path using the `Proffer.afterPath` event. I've included a link to the documentation.

Google Translate.
Puede cambiar la ruta utilizando el evento `Proffer.afterPath`. He incluido un enlace a la documentación.

https://github.com/davidyell/CakePHP3-Proffer/blob/master/docs/customisation.md#customising-upload-file-names-and-paths
