### ISSUE TITLE
Custom path

### ISSUE THREAD

**Issue by koprals** [davidyell/CakePHP3-Proffer#250]
Hi david,

I want to change 'dir' name from the deafult uuid to last insert id, can you give me an example to solve my problem david?

I try to use the pathClass, but i have some error and i got stuck.

**Comment by davidyell** [comment]
No, unfortunately I can't. If you are inserting a record, you will not know the inserted id until the record is inserted.

The only way around this issue would be to use the `[afterSave](https://book.cakephp.org/3.0/en/orm/table-objects.html#aftersave)` event, to move the file to a new folder, once you've saved it.
