### ISSUE TITLE
How do I get the uploaded image to display?

### ISSUE THREAD

**Issue by coyatsi** [davidyell/CakePHP3-Proffer#253]
I am still new on matters cakePHP. I have managed to successfully upload files but I cannot display them. From the manual:
`$this->Html->image('../files/<table>/<field>/' . $data->get('image_dir') . '/<prefix>_' . $data->get('image'));`
Am I supposed to replace the table and field with the actual names? What is $data? 
See my code below (baked), kindly point out any issues. 

**Controller**
 ```php
public function view($id = null)
    {
        $organiser = $this->Organisers->get($id, [
            'contain' => ['Events']
        ]);

        $this->set('organiser', $organiser);
        $this->set('_serialize', ['organiser']);
    }
```

**view.ctp**
```php
<?= $this->Form->create($organiser, ['type' => 'file']) ?>
        <?= $this->Form->input('name', array('label' => 'Organiser name')); ?>
        <?= $this->Form->input('about', array('label' => 'About','type' => 'textarea')); ?>
        <?= $this->Form->input('email', array('label' => 'Email', 'type' => 'email')); ?>
        <?= $this->Form->input('phone', array('label' => 'Phone')); ?>
        <?= $this->Html->image('../files/organisers/photo/' . $organiser->get('photo_dir') . '/<prefix>_' . $organiser->get('photo')); ?>
    <?= $this->Form->end() ?>
```

**Comment by davidyell** [comment]
The `<prefix>` is supposed to be replaced with your thumbnail prefix. So if you configure your thumbnail with `small` in the behaviour configuration, then that will be `/small_`.

If you look in your `/webroot/files` folders, you should be able to see the files with their prefixed names.

What is `$data`? That's the entity you pass to your form, so in your case `$organiser`.

**Comment by coyatsi** [comment]
Thank you!
