### ISSUE TITLE
problem when uploading associated photos

### ISSUE THREAD

**Issue by davizxtr** [davidyell/CakePHP3-Proffer#254]
Hi. I'm creating a project with cake3 and I'm using proffer.
I have adverts table that has many photos.
I can not save the photo association in adverts.

adverts table
```
$this->hasMany('Photos', [
            'foreignKey' => 'advert_id'
        ]);
```

photos table
```
$this->addBehavior('Proffer.Proffer', [
            'photo' => [
                'root' => WWW_ROOT . 'files',
                'dir' => 'photo_dir'
            ]
]);

$this->belongsTo('Adverts', [
            'foreignKey' => 'advert_id'
        ]);
```

in adverts controller
```
$advert = $this->Adverts->newEntity($this->request->getData(), ['associated'  =>  ['rates', 'photos', 'tags']]);
$this->Adverts->save($advert)
```

I followed the documentation.
I have a users table with a photo field for the avatar.
A photo is saved in a table but several in an associated table do not.

that could be happening?
In the adverts template to add advert:
`$this->Form->input('photos[]', ['label' => 'foto', 'type' => 'file', 'multiple' => true]);`

I appreciate the help.
Thank you very much

Best Regards

David.

**Comment by davidyell** [comment]
My first guess would be that your associations should be capitalised, as they're aliases. 

`'associated' => ['Rates', 'Photos', 'Tags']`

You might also want to use the `cascadeCallbacks` option when saving, to ensure that callbacks are executed, as this is how the plugin saves it's images.

**Comment by davizxtr** [comment]
Thanks for your reply.

I have tried what you have told me but it does not work.

I attached two images of debugkit:
1- The images are fine in the request data
![image](https://user-images.githubusercontent.com/37248385/37304027-aeaec830-2630-11e8-8dc3-9947d818a46b.png)

2- what returns newentity (Tags shows me well for example)
`$advert = $this->Adverts->newEntity($data, ['associated'  =>  ['Rates', 'Photos', 'Tags', 'Locations']]);`
![image](https://user-images.githubusercontent.com/37248385/37304116-057a6e62-2631-11e8-9c46-31e71bebdf59.png)

3- Photo Entity
![image](https://user-images.githubusercontent.com/37248385/37304292-70b47682-2631-11e8-9af0-2f3c3c1d4028.png)

4- Advert Entity
![image](https://user-images.githubusercontent.com/37248385/37304352-9cc71f68-2631-11e8-8c82-b1a7c6e0f06b.png)

I really appreciate your help.
Do you have any examples of associations in github?


Best Regards

David.

**Comment by davidyell** [comment]
I have a complete example app repository here, https://github.com/davidyell/CakePHP3-Proffer-Example

The PostsTable hasMany Uploads
https://github.com/davidyell/CakePHP3-Proffer-Example/blob/master/src/Model/Table/PostsTable.php#L51

Then I use the template array field input
https://github.com/davidyell/CakePHP3-Proffer-Example/blob/master/src/Template/Posts/edit.ctp#L24

**Comment by davizxtr** [comment]
Thank you very much.
works perfectly only with the` '*' => true`.
Because mine does not work for me? 
It works well but I still do not really know the problem in my entity..

![image](https://user-images.githubusercontent.com/37248385/37364970-480447a0-26fc-11e8-8da3-63e68ac8f71d.png)


Thanks for your time and for this great plugin.

Best Regards

David.

**Comment by davidyell** [comment]
That is to do with preventing Mass Assignment attacks. There is a section in the book on it. 

https://book.cakephp.org/3.0/en/orm/entities.html#mass-assignment
