### ISSUE TITLE
hasMany upload issue

### ISSUE THREAD

**Issue by spacebiscuit** [davidyell/CakePHP3-Proffer#258]
I'm trying to implemnt the hasMany image upload:

**ArticlesTable.php**

$this->hasMany('ArticleImages');  

**ArticleImagesTable.php**

```
$this->addBehavior('Proffer.Proffer', [
            'article_images' => [
                'root' => WWW_ROOT . 'img', 
                'dir' => 'dir',
                'thumbnailSizes' => [
                    'square' => [
                        'w' => 250,
                        'h' => 250,
			'fit' => true,
			'crop' => false,
                        'jpeg_quality'  => 100
                    ],
                    'portrait' => [
                        'w' => 150,
                        'h' => 200,
			'crop' => true,
                    ],
		    'landscape' => [
                        'w' => 400,
                        'h' => 300,
			'crop' => true,
			'fit' => true
                    ],
                ],
                'thumbnailMethod' => 'gd'   // Options are Imagick or Gd
            ],
]);

$this->belongsTo('Articles');

```

**View:**

```
echo $this->Form->create($article, ['type' => 'file']);
echo $this->Form->control('article_images[]', ['type' => 'file', 'multiple' => true, 'label' => 'Files to upload']);
```

**Controller:**

```
if ($this->request->is(['post', 'put'])) {
            $this->Articles->patchEntity($article, $this->request->getData(), ['associated' => ['ArticleImages']]);
            if ($this->Articles->save($article)) {
                $this->Flash->success(__('Your article has been updated.'));
                return $this->redirect(['action' => 'index']);
            }
            $this->Flash->error(__('Unable to update your article.'));
}
```

When I try to save I the ArticleImages table is populated but "dir" field is null and no file is uploaded to the server.

What am I doing wrong?

**Comment by spacebiscuit** [comment]
Since this is an edit action I am setting the entity no the form as follows:

`$article = $this->Articles->findById($id)->contain(['Authors', 'ArticleTypes', 'ArticleImages'])->firstOrFail();`

I didn't have the Progffer plugin enabled in my bootstrap.php, I have enabled it now but it makes no difference. I don't understand why my created and modified fields are also not saving, I have the Timestamp behaviour enabled on the Model tables

**Comment by davidyell** [comment]
Are you making any changes? Fields must be dirty for the save to happen

**Comment by spacebiscuit** [comment]
I just ensured a field was changed, but even before that I see an entry in ArticleImages minus the dir field, created and updated, again with no file uploaded.

Also if I put a die() in the first line of of the 'process' and 'beforeSave' methods in the ProfferBehaviour.php neither fires so I doesn't appear that the plugin is being recognised. I installed the package via composer as instructed and then enabled in the bootstrap.php - latest version of Cake3

**Comment by spacebiscuit** [comment]
Thought I would try a single image upload, changed the behaviour to the parent Table 'Articles', the ProfferBehaviour.php now fires but the $file var is null when the method moveUploadedFile is called. Tracing this back if I debug $upload in the foreach of the 'process' method the array 's indexes are all null. Not really sure what is going on but seems there is an issue with the plugin and the latest version of Cake perhaps?

**Comment by davidyell** [comment]
Great, thanks for the report. I will do some testing.

**Comment by spacebiscuit** [comment]
By the way, this is the fork that I created a few years back when I also couldn't get this to work, I just installed it and it enabled me to upload

=[https://github.com/spacebiscuit/CakePHP3-Proffer](url)

**Comment by davidyell** [comment]
Could be related to #256

**Comment by spacebiscuit** [comment]
Was this bug ever resolved? The problem is as follows:

ProfferBehavior.php :: 78

$entity->get($field)['error']

When the upload field is multiple files the request data is as follows:

```
'article_images' => [
		(int) 0 => object(App\Model\Entity\ArticleImage) {

			'tmp_name' => 'C:\wamp64\tmp\phpBD6E.tmp',
			'error' => (int) 0,
```
There for the check for the error should be:

$entity->get($field)[0]['error']

Unless I am missing something in my config?
