### ISSUE TITLE
 Upload files with jsonapi

### ISSUE THREAD

**Issue by davizxtr** [davidyell/CakePHP3-Proffer#259]
Hi.

I have implemented the plugin on a website and it works perfectly.
I am trying to upload images through jsonapi sending the image in base64 but it does not work.
I would like to know if it is possible to do so and what would have to be configured.

thanks.

```
PATH
Content-Type: application/vnd.api+json
Accept: application/vnd.api+json
{
  "data": {
    "type": "adverts",
    "id": "121",
    "attributes": {},
    "relationships": {
      "photos": {
    	"data": [{ 
        	"type": "photos", 
        	"id": "1",
        	"attributes": {
        		"photo": "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAA ...
```

**Comment by davidyell** [comment]
No, this is not possible, or at least I've never tried to do this.
