### ISSUE TITLE
HEIC image format is not supported 

### ISSUE THREAD

**Issue by anil-kumar-pal** [davidyell/CakePHP3-Proffer#263]
It's throwing an exception: 
`[Intervention\Image\Exception\NotSupportedException] Encoding format (HEIC) is not supported`
When I tried to upload image file with format .heic

**Comment by davidyell** [comment]
Thanks for letting me know, but this looks to be an issue with Intervention Image which is the image processing library that I use. Please raise an issue on that repo. Thanks!
