### ISSUE TITLE
Depreciation Cake 3.6

### ISSUE THREAD

**Issue by spacebiscuit** [davidyell/CakePHP3-Proffer#264]
Since updating my Cake version to v3.6 I am getting the following depreciation warnings:

`
Deprecated (16384): App\Model\Table\LinkImagesTable::schema() is deprecated. Use setSchema()/getSchema() instead. - vendor/davidyell/proffer/src/Model/Behavior/ProfferBehavior.php, line: 38

Should I just disable warnings and assume this will be addressed in a possible plugin update or is there something in my own config causing this error?

Thanks as always - I love this plugin :)

**Comment by davidyell** [comment]
The plugin needs to be updated to match the latest release of CakePHP, that's all.

You can safely disable the deprecation warnings and everything will still work.
