### ISSUE TITLE
Error to Upload multiple images

### ISSUE THREAD

**Issue by TNDdesarrollo** [davidyell/CakePHP3-Proffer#271]
Hi, recent I installed de plugin I works perfectly when just upload one image, So I'm trying to follow the documentation, But Im not clear how upload multiple images, when Im add new product cap the products but I dont know where its saved, And how I call them In the view. I have some questions:

1. How look have the table Uploads?
2. I need to create a table for the image?
3. If I want multiple uploads I need add photo and photo_dir to my products table?
4. How I call all the images to the view of the product?

Note: I'm start in cakephp a few months ago, so Im new.

I use cakephp 3.7

**Comment by davidyell** [comment]
https://github.com/davidyell/CakePHP3-Proffer/blob/master/docs/examples.md#uploading-multiple-related-images
