### ISSUE TITLE
I can't use multiple upload

### ISSUE THREAD

**Issue by davidecantoni-cdinformatica** [davidyell/CakePHP3-Proffer#272]
Hi,
I'm new to proffer and I can't use multiple upload to an entity.
I have Quotations with many Uploads.
My table are:

QuotationsTable.php
>
>        $this->hasMany('Uploads', [
>             'foreignKey' => 'quotation_id'
>         ]);
>

UploadsTable.php

> 
>   $this->belongsTo('Quotations', [
>           'foreignKey' => 'quotation_id',
>           'joinType' => 'INNER'
>         ]);
>

>         
>         $this->addBehavior('Proffer.Proffer', [
>                 'filename' => [	
>                                'root' => WWW_ROOT . 'files', 
>                                 'dir' => 'dir'	
>                 ]
>         ]);
>

 In my Quotations edit.ctp:
>
> <?php echo $this->Form->control('filename[]' , ['label' => 'Allegato','type' => 'file','multiple' => true]);?>
>
On submit there is no data in database e no file uploades in webroot/files/ecc...

Where I'm wrong???

**Comment by davidyell** [comment]
You've attached the behaviour to the wrong table class.

Please check the documentation https://github.com/davidyell/CakePHP3-Proffer/blob/master/docs/examples.md#uploading-multiple-related-images

**Comment by davidecantoni-cdinformatica** [comment]
I've moved the behaviour on QuotationsTable.php, but the error remain... no data in db e no file uploaded.

QuotationsTable.php

```
> $this->hasMany('Uploads', [
>             'foreignKey' => 'quotation_id'
>         ]);
>         //FR - comportamento al caricamneto dei file
>         $this->addBehavior('Proffer.Proffer', [
>                 'filename' => [	// The name of your upload field
>                                'root' => WWW_ROOT . 'files', // Customise the root upload folder here, or omit to use the default
>                                 'dir' => 'dir'	// The name of the field to store the folder
>                 ]
>         ]);
```

**Comment by davidyell** [comment]
Is your upload input an array?
Does it have the name `Uploads.filename`?

**Comment by davidecantoni-cdinformatica** [comment]
Yes...
my UploadsTable.php
![image](https://user-images.githubusercontent.com/51787507/59445372-d585bf80-8dff-11e9-849c-921d4df18261.png)

my QuotationsTable.php
![image](https://user-images.githubusercontent.com/51787507/59445401-e1718180-8dff-11e9-8c85-cf16730aadcf.png)

my edit.ctp in quotations
![image](https://user-images.githubusercontent.com/51787507/59445438-f817d880-8dff-11e9-9e63-313e01d05d4f.png)

my Quotation and Upload Entity:
![image](https://user-images.githubusercontent.com/51787507/59445516-15e53d80-8e00-11e9-9d24-fc2176f1f595.png)


Still no data uploaded e no data in db...

**Comment by davidyell** [comment]
Is your form a multi-part form type?

**Comment by davidecantoni-cdinformatica** [comment]
yes
![image](https://user-images.githubusercontent.com/51787507/59447966-82fad200-8e04-11e9-97aa-c38e5c2b0a81.png)

**Comment by davidyell** [comment]
As it's a property, wouldn't that be `->control('uploads[])`.

See my example application for an example, https://github.com/davidyell/CakePHP3-Proffer-Example/blob/master/src/Template/Posts/add.ctp
