### ISSUE TITLE
Upload to aws s3

### ISSUE THREAD

**Issue by lrnzfrr** [davidyell/CakePHP3-Proffer#281]
is there a best practice to upload / transfer  to aws s3?

**Comment by davidyell** [comment]
No sorry, the plugin does not support AWS. The friendsofcake/cakephp-upload plugin allows for custom writer classes which you could use with phpleague/fly-system to upload to AWS.

Hope this helps.

**Comment by lrnzfrr** [comment]
> No sorry, the plugin does not support AWS. The friendsofcake/cakephp-upload plugin allows for custom writer classes which you could use with phpleague/fly-system to upload to AWS.
> 
> Hope this helps.
yes i'm using cakephp-upload! 
Anyway thanks for your great plugin!
