### ISSUE TITLE
Proffer  for cake4 does not download

### ISSUE THREAD

**Issue by kucko** [davidyell/CakePHP3-Proffer#288]
![image](https://user-images.githubusercontent.com/434077/124675879-26532f80-de83-11eb-9ba1-529e36137ca4.png)

**Comment by davidyell** [comment]
Not sure you need those quotes, looking at the error it thinks the package name is `'davidyell/proffer`

**Comment by kucko** [comment]
Thanks for answering. Sorry I did not write my concern. I am trying to download the package compatible with cakephp4 I enter the command as indicated in the manual and it throws me that error. Could you tell me which package is compatible with cakephp4

**Comment by davidyell** [comment]
I think you have it right, just need to either not use those backticks, or proper apostrophes.

You could try the tagged alpha release https://packagist.org/packages/davidyell/proffer#2.0.0-alpha1

**Comment by kucko** [comment]
Hey man what a shame clear the quotes. I have several days with this problem of uploading files that I no longer saw. Thank you very much were the quotes. I will be testing this plugin for cakephp4
Again thank you very much
