### ISSUE TITLE
Detect if fileinfo module is loaded for the function(s)/class finfo()

### ISSUE THREAD

**Issue by M-pire** [davidyell/CakePHP3-Proffer#29]
While implementing the Proffer code, PHP threw me an error telling me that:

> Fatal error: Class 'finfo' not found in /home/...../...../finfo.php on line 4

I was able to resolve the issue enabling the fileinfo extension in php.ini . If people have the same problem, read this post: http://stackoverflow.com/questions/3579072/php-fileinfo-is-undefined-function

To resolve the issue I suggest to detect if the module is loaded yes/no and maybe create/use a fallback for it. Otherwise, maybe add it to the requirements of the plugin.

p.s. Even though the requirements say PHP5.4+ ( fileinfo was introduced in PHP5.3 i think ), it could be disabled in the php.ini of the server.

Thanks for the plugin!

**Comment by davidyell** [comment]
Thanks for the issue. I'll see if I can remove the dependency on this or work around it.
