### ISSUE TITLE
Problem in ImageTransform.php

### ISSUE THREAD

**Issue by caBBAlainB** [davidyell/CakePHP3-Proffer#31]
Hello,
I found a problem in thumbnailCropScale() method

Original code:

	protected function thumbnailCropScale(ImageInterface $image, $targetWidth, $targetHeight)
	{
		$target = new Box($targetWidth, $targetHeight);
		$sourceSize = $image->getSize();
		if ($sourceSize->getWidth() > $sourceSize->getHeight()) {
			$width = $sourceSize->getWidth() * ($target->getHeight() / $sourceSize->getHeight());
			$cropPoint = new Point((int)(max($width - $target->getWidth(), 0) / 2), 0);
		} else {
			$height = $sourceSize->getHeight() * ($target->getWidth() / $sourceSize->getWidth());
			$cropPoint = new Point(0, (int)(max($height - $target->getHeight(), 0) / 2));
		}
		$box = new Box($targetWidth, $targetHeight);
		return $image->thumbnail($box, ImageInterface::THUMBNAIL_OUTBOUND)
		->crop($cropPoint, $target);
	}

According to that code, an image of 3008 x 2000 (http://i.imgur.com/WwG9fGt.jpg) will be resize to 500 x 332.
Then when we ask Imagine to crop it to 500 x 500 for example, it will extend the width of 332 with a black border (http://i.imgur.com/MeeXNxY.jpg).

The solution is to ask Imagine to resize the image based on targetHeight for a landscape image and on targetWidth for a portrait image.

That way, Imagine will resize it to 752 x 500, which can be cropped correctly to 500 x 500 (http://i.imgur.com/rLg4s5s.jpg)

Fixed code:

	protected function thumbnailCropScale(ImageInterface $image, $targetWidth, $targetHeight)
	{
		$target = new Box($targetWidth, $targetHeight);
		$sourceSize = $image->getSize();
		if ($sourceSize->getWidth() > $sourceSize->getHeight()) {
			$width = $sourceSize->getWidth() * ($target->getHeight() / $sourceSize->getHeight());
			$height = $targetHeight;
			$cropPoint = new Point((int)(max($width - $target->getWidth(), 0) / 2), 0);
		} else {
			$height = $sourceSize->getHeight() * ($target->getWidth() / $sourceSize->getWidth());
			$width = $targetWidth;
			$cropPoint = new Point(0, (int)(max($height - $target->getHeight(), 0) / 2));
		}
		$box = new Box($width, $height);
		return $image->thumbnail($box, ImageInterface::THUMBNAIL_OUTBOUND)
		->crop($cropPoint, $target);
	}

Regards,

**Comment by davidyell** [comment]
I've implemented your fix, thanks for the code.

**Comment by caBBAlainB** [comment]
NP, I'm pleased to help you.
