### ISSUE TITLE
thumbnail crop fatal error

### ISSUE THREAD

**Issue by TomCurry** [davidyell/CakePHP3-Proffer#37]
tried to upload an image that was smaller than the thumbnail sizes and got an error. I was expecting the image to stay the same size.

**Comment by davidyell** [comment]
I am unable to reproduce this issue. Are you able to let me know some more details about this.

* A gist of your tables Proffer configuration, specifically the thumbnail sizes
* The dimensions and file type of the image
* Or better yet, the actual image

Thanks

**Comment by TomCurry** [comment]
updated to 0.0.6 and it seems to be working

**Comment by davidyell** [comment]
Good news everyone! :clap:
