### ISSUE TITLE
Handling moving/uploading processing of file in afterSave

### ISSUE THREAD

**Issue by dakota** [davidyell/CakePHP3-Proffer#46]
Since the save might still fail after the beforeSave callback, it would be better to handle the processing of the uploaded file in the afterSave callback.

**Comment by ADmad** [comment]
Even `afterSave` isn't ideal as for an atomic save the transaction could be rolled back later. Which is why I am adding a new [afterSaveCommit](https://github.com/cakephp/cakephp/pull/5972) event.

**Comment by davidyell** [comment]
http://book.cakephp.org/3.0/en/orm/table-objects.html#aftersavecommit

**Comment by ADmad** [comment]
After some rethinking I personally kept the file uploading in beforeSave itself. Move file and update required entity property. Even if the transaction does get rolledback you end up with an extra file in your filesystem (any other storage) which isn't a big deal imo.

Also the `afterSaveCommit` is only triggered for primary model so if you were uploading file for an associated model it wouldn't work.

**Comment by davidyell** [comment]
Ah, that's a good point. I have a shell task for cleaning up 'left over' images too, so extra weight on the filesystem isn't a huge big deal.

**Comment by davidyell** [comment]
Related to #100 

I'm going to close this ticket now, as I'm happy with the API, and it doesn't seem to be generating any issues. Plus once the changes in #100 are completed, it will close this loophole.
