### ISSUE TITLE
Typo in README.md: missing "]"

### ISSUE THREAD

**Issue by M-pire** [davidyell/CakePHP3-Proffer#49]
The updated README.md contains a syntax/typing error:
Current:
`Plugin::load('Proffer', ['bootstrap' => true);`

Should be:
`Plugin::load('Proffer', ['bootstrap' => true]);`

**Comment by davidyell** [comment]
Ooh, good spot, thanks! I'll get that updated

**Comment by M-pire** [comment]
Also: the new version of Proffer fixes my issues with the file upload. Tested it couple minutes ago and is working now. Thanks! Saved my (work)life!
