### ISSUE TITLE
Create a FAQ or common errors?

### ISSUE THREAD

**Issue by davidyell** [davidyell/CakePHP3-Proffer#67]
It might be worth collating the various common errors that people might experience when using the plugin so that solutions to them are readily available.

Eg,
`Unknown type "proffer.file"`
Would be a missing `'bootstrap' => true` in the loading of the plugin.

**Comment by M-pire** [comment]
Was just reading this issue and wanted to add that `unknown type "proffer.file"` can also occur when the user has not added the database type for Proffer to the model table. I'm talking about this code:

```php
protected function _initializeSchema(\Cake\Database\Schema\Table $table) {
	$table->columnType('file','proffer.file');
	return $table;
}
```

Which could also give people problems, like saving "Array" to the database. Which can also occur when `"type"=>"file"`is forgotten. I know you know this, but might be good to add it to this issue log to easily create documentation page for it later.

Thanks!
