### ISSUE TITLE
Customize file path 

### ISSUE THREAD

**Issue by damianoporta** [davidyell/CakePHP3-Proffer#72]
Hi,
I think we should allow more costomization of the file path.
Following the doc (https://github.com/davidyell/CakePHP3-Proffer/blob/master/docs/examples/UploadFilenameListener.md) we only can change filename and seed. 

What about if i do not have to deal with the table name?

`setTable` (https://github.com/davidyell/CakePHP3-Proffer/blob/master/src/Lib/ProfferPath.php#L91) is a protected method, we should set it to public and change `fullPath` (https://github.com/davidyell/CakePHP3-Proffer/blob/master/src/Lib/ProfferPath.php#L208) method to manage empty '' table.

**Comment by davidyell** [comment]
Yes, I don't see that being a problem. The documentation would need to be updated to reflect the change.

**Comment by davidyell** [comment]
I'll take care of this.

**Comment by davidyell** [comment]
Superseded by #85
