### ISSUE TITLE
Test custom events

### ISSUE THREAD

**Issue by davidyell** [davidyell/CakePHP3-Proffer#73]
The new events which the plugin emits are not tested anywhere. It would be wise to add some tests which just ensure that the events are bound properly and get fired when the code is executed.

Otherwise there is no way to guarantee that the events exist for when people want to use them to customise aspects of the plugin.

**Comment by bobmulder** [comment]
Hey David,

We talked at the freenode chat of CakePHP about this issue. I got something like this:

```
$eventManager->expects($this->at(0))->method('dispatch')
            ->with($this->logicalAnd(
                    $this->isInstanceOf('Cake\Event\Event'), 
                    $this->attributeEqualTo('_name', 'Component.Manager.beforeFilter')
            ))
            ->will($this->returnValue($this->getMock('Cake\Event\Event', null, [], '', false)));
```

This seems to work pretty well...

**Comment by davidyell** [comment]
Ah yes. Much better than my attempt this afternoon.

**Comment by bobmulder** [comment]
That's what I thought ;) Well, I think there are many ways to do this... It depends on what you're testing... A flow, or a single event. When you want to test a single event you might like this:

```
        $eventManager->expects($this->once())->method('dispatch')
            ->with($this->logicalAnd(
                    $this->isInstanceOf('Cake\Event\Event'), $this->attributeEqualTo('_name', 'Component.Manager.startup')
            ))
            ->will($this->returnValue($this->getMock('Cake\Event\Event', null, [], '', false)));
```

**Comment by bobmulder** [comment]
@davidyell What about this? https://github.com/cakemanager/cakephp-cakemanager/blob/develop/tests/TestCase/Controller/Component/ManagerComponentTest.php
