### ISSUE TITLE
Notice: Undefined index: thumbnailSizes

### ISSUE THREAD

**Issue by michelpeters** [davidyell/CakePHP3-Proffer#88]
**Situation**
If I understand it correctly, `thumbnailSizes` became optional after davidyell/CakePHP3-Proffer#83 . I have added the Proffer behavior to my `ProjectFiles` model table like this:

```php
$this->addBehavior('Proffer.Proffer',[ 
	'file_name' => [ 
		'dir' => 'file_dir'
	] 
]);
```

thus, leaving out `thumbnailSizes` from the configuration array for the behavior.  

**Problem**
On deleting a ProjectFile record that has no `thumbnailSizes` set, I get this notice:

`Notice (8): Undefined index: thumbnailSizes [ROOT\vendor\davidyell\proffer\src\Model\Behavior\ProfferBehavior.php, line 119]`

**Solution**
Looking at the code in ProfferBehavior:119, it could be fixed adding a isset/empty check on `$settings['thumbnailSizes']`. 

Soon I'll try to fix/write the code myself instead of only creating issues.

Thx again!

**Comment by davidyell** [comment]
Argh, that's a regression I've introduced with my PR. I'll have to create a test for this and a fix.
