### ISSUE TITLE
Cleanup with support for multiple subdirectories.

### ISSUE THREAD

**Issue by designway** [davidyell/CakePHP3-Proffer#99]
For some filesystems the directory can contain a maximum of folders.
ext2: maximum 32768 folders
ext3: maximum 31998 folders

So i created UploadFilenameListener to change upload directory. Because my database contains 90k products, which generates 90k folders. But splitting up the folderstructure I dont have any limitations anymore.

My folder structure looks now like:
```
/43/62/1/bp28.jpg
/45/40/2/bp92.jpg
/45/40/2/bp9.jpg
/4c/ba/3/bp8.jpg
```

That way ill never get stuck at the maximum folders.

But when running Cleanup from the shell:
```
bin/cake proffer.proffer cleanup --dry-run Products
Performing dry run cleanup.
Would remove folder `43`
Would remove folder `45`
Would remove folder `4c`
```
Warning Error: rmdir(...files\shops\photo\4c): Directory not empty

But these folders are not empty, they just contain subfolder/subfolder/file..

When running "bin/cake proffer.proffer generate Products" it works fine!
```
Thumbnails regenerated for Products bp28.jpg
Thumbnails regenerated for Products bp92.jpg
Thumbnails regenerated for Products bp9.jpg
Thumbnails regenerated for Products bp8.jpg
```

My Listner looks like:

    public function change(Event $event, ProfferPath $path)
    {
        $hash = Security::hash($event->subject()->get('id'), 'md5', true);
        $folderA = substr($hash, 0, 2);
        $folderB = substr($hash, 2, 2);

        $path->setSeed($folderA . DS . $folderB);

        return $path;
    }

**Comment by davidyell** [comment]
Yes, this is detailed in #81 

Due to the custom listener changing the path, the shell cannot understand your new paths. It's on my todo list to update this to use the custom listener class in the shell to be able to clean the old files properly.
